import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import './styles.css';

const SUPABASE_URL=import.meta.env.VITE_SUPABASE_URL as string|undefined;
const SUPABASE_KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string|undefined;
const supabase=(SUPABASE_URL&&SUPABASE_KEY)?createClient(SUPABASE_URL,SUPABASE_KEY):null;
// Configure VITE_APP_URL in Vercel with the canonical production address.
// The fallback keeps all e-mail links out of localhost in production.
const configuredAppUrl=import.meta.env.VITE_APP_URL as string|undefined;
const APP_URL=(configuredAppUrl||'https://contas-da-casa-six-sigma.vercel.app').replace(/\/$/,'');
const authRedirect=(path:string)=>`${APP_URL}${path}`;
const isRecoveryRequest=()=>new URLSearchParams(window.location.hash.slice(1)).get('type')==='recovery'||new URLSearchParams(window.location.search).get('type')==='recovery';
const familyId='00000000-0000-0000-0000-000000000001';

type Expense={id:string;expense_date:string;amount:number;description:string;recipient?:string;category_id:string;payment_method_id?:string;paid_by_user_id?:string};
const brl=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
function App(){
 const [session,setSession]=useState<any>(null); const [tab,setTab]=useState('inicio'); const [expenses,setExpenses]=useState<Expense[]>([]);
 const [cats,setCats]=useState<any[]>([]); const [methods,setMethods]=useState<any[]>([]); const [users,setUsers]=useState<any[]>([]);
 const [loading,setLoading]=useState(true); const [recoveryMode,setRecoveryMode]=useState(isRecoveryRequest);
 useEffect(()=>{if(!supabase){setLoading(false);return;} supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data}=supabase.auth.onAuthStateChange((event,s)=>{if(event==='PASSWORD_RECOVERY')setRecoveryMode(true);setSession(s)}); return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session) load();},[session]);
 async function load(){if(!supabase)return; setLoading(true); const [e,c,m,u]=await Promise.all([
  supabase.from('expenses').select('*').eq('family_id',familyId).order('expense_date',{ascending:false}),
  supabase.from('categories').select('*').eq('family_id',familyId).eq('active',true).order('name'),
  supabase.from('payment_methods').select('*').eq('family_id',familyId).eq('active',true).order('name'),
  supabase.from('family_users').select('*').eq('family_id',familyId).order('name')]);
 setExpenses(e.data||[]);setCats(c.data||[]);setMethods(m.data||[]);setUsers(u.data||[]);setLoading(false)}
 if(window.location.pathname==='/atualizar-senha'||recoveryMode) return <UpdatePassword recoveryMode={recoveryMode}/>;
 if(!session) return <Auth onDone={setSession}/>;
 const total=expenses.reduce((s,e)=>s+Number(e.amount),0);
 return <div className="app"><header><div><span className="eyebrow">CONTAS DA CASA</span><h1>{tab==='inicio'?'Olá, família 👋':tab==='novo'?'Novo gasto':tab==='historico'?'Histórico':'Configurações'}</h1></div><button onClick={()=>supabase?.auth.signOut()} style={{background:'white',border:'1px solid #e4e4e7',borderRadius:12,padding:'10px 13px',color:'#52525b',fontWeight:700}}>Sair</button></header>
 <main>{tab==='inicio'&&<Home total={total} expenses={expenses} cats={cats} setTab={setTab}/>}
 {tab==='novo'&&<NewExpense cats={cats} methods={methods} users={users} onSaved={load}/>}
 {tab==='historico'&&<History expenses={expenses} cats={cats} methods={methods}/>}
 {tab==='config'&&<Settings cats={cats} methods={methods} onChanged={load}/>}
 </main>
 <nav>{[['inicio','⌂','Início'],['novo','＋','Novo'],['historico','⌕','Histórico'],['config','⚙','Ajustes']].map(([k,i,l])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}><b>{i}</b><span>{l}</span></button>)}</nav></div>
}
function Auth({onDone}:{onDone:(s:any)=>void}){const [email,setEmail]=useState('');const [pass,setPass]=useState('');const [name,setName]=useState('');const [signup,setSignup]=useState(false);const [forgot,setForgot]=useState(false);const [msg,setMsg]=useState('');const [sending,setSending]=useState(false); async function go(){if(!supabase){setMsg('Configure as variáveis do Supabase no Vercel.');return} setMsg(''); let r=signup?await supabase.auth.signUp({email,password:pass,options:{data:{name},emailRedirectTo:authRedirect('/')}}):await supabase.auth.signInWithPassword({email,password:pass}); if(r.error)setMsg(r.error.message);else if(r.data.session)onDone(r.data.session);else setMsg('Verifique seu e-mail para confirmar o cadastro.')} async function reset(){if(!supabase){setMsg('Configure as variáveis do Supabase no Vercel.');return}if(!email){setMsg('Informe seu e-mail para receber o link.');return}setSending(true);setMsg('');const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:authRedirect('/atualizar-senha')});setSending(false);setMsg(error?error.message:'Se houver uma conta com este e-mail, você receberá um link para criar uma nova senha.')} return <div className="auth"><div className="brand">💰</div><span className="eyebrow">CONTAS DA CASA</span><h1>{forgot?'Recupere sua senha':<>Seu dinheiro,<br/>sua memória.</>}</h1><p>{forgot?'Informe seu e-mail. Enviaremos um link seguro para você definir uma nova senha.':'Registre o contexto de cada gasto para nunca mais precisar adivinhar o que foi aquele pagamento.'}</p>{signup&&<input placeholder="Seu nome" value={name} onChange={e=>setName(e.target.value)}/>}<input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/>{!forgot&&<input type="password" placeholder="Senha" value={pass} onChange={e=>setPass(e.target.value)}/>} {msg&&<div className="msg">{msg}</div>}<button className="primary" disabled={sending} onClick={forgot?reset:go}>{forgot?(sending?'Enviando...':'Enviar link de recuperação'):signup?'Criar minha conta':'Entrar'}</button>{!signup&&!forgot&&<button className="link" onClick={()=>{setForgot(true);setMsg('')}}>Esqueci minha senha</button>}<button className="link" onClick={()=>{setSignup(!signup);setForgot(false);setMsg('')}}>{forgot?'Voltar ao login':signup?'Já tenho uma conta':'Criar minha conta'}</button></div>}
function UpdatePassword({recoveryMode}:{recoveryMode:boolean}){const [ready,setReady]=useState(false);const [pass,setPass]=useState('');const [confirm,setConfirm]=useState('');const [msg,setMsg]=useState('');const [saving,setSaving]=useState(false);useEffect(()=>{if(!supabase){setMsg('Configure as variáveis do Supabase no Vercel.');return}supabase.auth.getSession().then(({data})=>setReady(Boolean(data.session)&&recoveryMode));const {data}=supabase.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY')setReady(Boolean(session));});return()=>data.subscription.unsubscribe()},[recoveryMode]);async function save(){if(!supabase)return;if(pass.length<6){setMsg('A nova senha precisa ter pelo menos 6 caracteres.');return}if(pass!==confirm){setMsg('As senhas não coincidem.');return}setSaving(true);setMsg('');const {error}=await supabase.auth.updateUser({password:pass});setSaving(false);if(error){setMsg(error.message);return}setMsg('Senha atualizada com sucesso. Você já pode entrar.')}async function backToLogin(){await supabase?.auth.signOut();window.location.assign('/')}return <div className="auth"><div className="brand">💰</div><span className="eyebrow">CONTAS DA CASA</span><h1>Crie uma nova senha</h1><p>{ready?'Escolha uma senha nova para voltar a acessar suas contas.':'Este link de recuperação é inválido ou expirou. Solicite um novo link na tela de login.'}</p>{ready&&<><input type="password" placeholder="Nova senha" value={pass} onChange={e=>setPass(e.target.value)}/><input type="password" placeholder="Confirme a nova senha" value={confirm} onChange={e=>setConfirm(e.target.value)}/></>}{msg&&<div className="msg">{msg}</div>}{ready?<button className="primary" disabled={saving} onClick={save}>{saving?'Salvando...':'Atualizar senha'}</button>:null}<button className="link" onClick={backToLogin}>{msg.startsWith('Senha atualizada')?'Ir para o login':'Voltar ao login'}</button></div>}
function Home({total,expenses,cats,setTab}:{total:number;expenses:Expense[];cats:any[];setTab:any}){return <><section className="hero"><span>Gastos de agosto</span><strong>{brl.format(total)}</strong><small>{expenses.length} registros</small></section><button className="add" onClick={()=>setTab('novo')}><span>＋</span><div><b>Novo gasto</b><small>Registre em poucos segundos</small></div><i>›</i></button><div className="sectionhead"><h2>Últimos gastos</h2><button onClick={()=>setTab('historico')}>Ver todos</button></div><div className="list">{expenses.slice(0,6).map(e=><ExpenseRow key={e.id} e={e} cats={cats}/>)}</div></>}
function ExpenseRow({e,cats}:{e:Expense;cats:any[]}){return <div className="row"><div className="dot">{(cats.find(c=>c.id===e.category_id)?.name||'O').slice(0,1)}</div><div className="grow"><b>{e.description}</b><small>{cats.find(c=>c.id===e.category_id)?.name||'Sem categoria'}{e.recipient?` · ${e.recipient}`:''}</small></div><strong>{brl.format(e.amount)}</strong></div>}
function NewExpense({cats,methods,users,onSaved}:{cats:any[];methods:any[];users:any[];onSaved:()=>void}){const [f,setF]=useState<any>({expense_date:new Date().toISOString().slice(0,10),amount:'',description:'',category_id:cats[0]?.id||'',payment_method_id:methods[0]?.id||'',paid_by_user_id:users[0]?.id||'',recipient:''});const [saving,setSaving]=useState(false);async function save(){if(!supabase||!f.amount||!f.description)return;setSaving(true);const {error}=await supabase.from('expenses').insert({...f,amount:Number(String(f.amount).replace(',','.')),family_id:familyId,registered_by_user_id:users[0]?.id});setSaving(false);if(error){alert(`Não foi possível salvar: ${error.message}`);return}setF({...f,amount:'',description:'',recipient:''});onSaved();alert('Gasto salvo!')}return <section><div className="card"><label>Quanto?</label><input className="amount" inputMode="decimal" placeholder="R$ 0,00" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/><label>O que foi?</label><input placeholder="Ex.: compra do supermercado" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><label>Para quem? <em>opcional</em></label><input placeholder="Ex.: Maria" value={f.recipient} onChange={e=>setF({...f,recipient:e.target.value})}/><label>Categoria</label><select value={f.category_id} onChange={e=>setF({...f,category_id:e.target.value})}>{cats.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><label>Meio de pagamento</label><select value={f.payment_method_id} onChange={e=>setF({...f,payment_method_id:e.target.value})}>{methods.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select><label>Quem pagou?</label><select value={f.paid_by_user_id} onChange={e=>setF({...f,paid_by_user_id:e.target.value})}>{users.map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select><label>Data</label><input type="date" value={f.expense_date} onChange={e=>setF({...f,expense_date:e.target.value})}/><button className="primary" disabled={saving} onClick={save}>{saving?'Salvando...':'Salvar gasto'}</button></div><Assistant/></section>}
function Assistant(){const [text,setText]=useState('');const [preview,setPreview]=useState<any>(null);function parse(){const m=text.match(/R\$?\s*([\d.,]+)/i);const amount=m?Number(m[1].replace(/\./g,'').replace(',','.')):null;const pm=/\bpix\b/i.test(text)?'Pix':/\bcart[aã]o\b/i.test(text)?'Cartão':null;setPreview({amount,description:text,method:pm})}return <div className="assistant"><b>✨ Assistente</b><p>Digite como você falaria normalmente.</p><input placeholder='“Paguei R$ 180 para Maria no Pix”' value={text} onChange={e=>setText(e.target.value)}/><button onClick={parse}>Interpretar</button>{preview&&<div className="preview"><small>Confira antes de salvar</small><b>{preview.amount?brl.format(preview.amount):'Valor não identificado'}</b><span>{preview.method||'Meio de pagamento não identificado'}</span><span>{preview.description}</span></div>}</div>}
function History({expenses,cats,methods}:{expenses:Expense[];cats:any[];methods:any[]}){const [q,setQ]=useState('');const filtered=expenses.filter(e=>e.description.toLowerCase().includes(q.toLowerCase())||(e.recipient||'').toLowerCase().includes(q.toLowerCase()));return <section><input className="search" placeholder="🔎  Buscar gasto..." value={q} onChange={e=>setQ(e.target.value)}/><div className="list">{filtered.map(e=><ExpenseRow key={e.id} e={e} cats={cats}/>)}</div></section>}
function Settings({cats,methods,onChanged}:{cats:any[];methods:any[];onChanged:()=>void}){return <section><div className="card"><h2>Categorias</h2>{cats.map(c=><div className="settingrow" key={c.id}>{c.name}<span>✓</span></div>)}</div><div className="card"><h2>Meios de pagamento</h2>{methods.map(m=><div className="settingrow" key={m.id}>{m.name}<span>✓</span></div>)}</div></section>}
createRoot(document.getElementById('root')!).render(<App/>);
